import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import type { PrescriptionResponse } from "../../types/prescription.types";
import { getPatientPrescriptions } from "../../api/prescriptionApi";
import { getDoctorById } from "../../api/doctorApi";
import jsPDF from "jspdf";

function MyPrescriptions() {
  const [prescriptions, setPrescriptions] = useState<PrescriptionResponse[]>(
    [],
  );
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [doctorNames, setDoctorNames] = useState<{ [key: number]: string }>({});

  const navigate = useNavigate();

  useEffect(() => {
    fetchData();
  }, []);

  async function fetchData() {
    try {
      const data = await getPatientPrescriptions();

      setPrescriptions(data);

      const doctorNamesMap: { [key: number]: string } = {};

      for (const prescription of data) {
        if (!doctorNamesMap[prescription.doctorId]) {
          try {
            const doctor = await getDoctorById(prescription.doctorId);

            doctorNamesMap[prescription.doctorId] = doctor.name;
          } catch {
            doctorNamesMap[prescription.doctorId] = "Unknown Doctor";
          }
        }
      }

      setDoctorNames(doctorNamesMap);
    } catch (err) {
      setError("Failed to fetch prescriptions!");
    } finally {
      setLoading(false);
    }
  }

  function handleDownloadPDF(prescription: PrescriptionResponse) {
    const doc = new jsPDF();

    //Header
    doc.setFontSize(20);
    doc.setTextColor(0, 102, 204);
    doc.text("MediConnect", 105, 20, { align: "center" });

    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("Medical Prescription", 105, 30, { align: "center" });

    //Divider Line
    doc.setDrawColor(0, 102, 204);
    doc.line(20, 35, 190, 35);

    //Doctor Info

    doc.setFontSize(12);
    doc.text(
      `Doctor: Dr. ${doctorNames[prescription.doctorId] || "Unknown"}`,
      20,
      45,
    );

    doc.text(`Prescription #${prescription.id}`, 20, 55);
    doc.text(`Date: ${formatDate(prescription.prescribedAt)}`, 20, 65);
    doc.text(`Appointment ID: #${prescription.appointmentId}`, 20, 75);

    //Divider
    doc.line(20, 80, 190, 80);

    //Instructions
    doc.setFontSize(12);
    doc.setTextColor(0, 102, 204);
    doc.text("Instructions:", 20, 90);
    doc.setTextColor(0, 0, 0);

    const instructions = doc.splitTextToSize(
      prescription.instructions || "N/A",
      170,
    );

    doc.text(instructions, 20, 100);

    //Medicines
    doc.setTextColor(0, 102, 204);
    doc.text("Medicines:", 20, 115);
    doc.setTextColor(0, 0, 0);

    let yPosition = 125;

    prescription.medicines.forEach((medicine, index) => {
      doc.text(
        `${index + 1}. ${medicine.name} | ${medicine.dosage} | ${medicine.frequency} | ${medicine.duration}`,
        25,
        yPosition,
      );
      yPosition += 10;
    });

    //Footer

    doc.setDrawColor(0, 102, 204);
    doc.line(20, yPosition + 5, 190, yPosition + 5);
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text(
      "Generated by MediConnect - Your Health, Our Priority",
      105,
      yPosition + 15,
      { align: "center" },
    );

    //Download

    doc.save(`prescription-${prescription.id}.pdf`);
  }

  function formatDate(dateString: string) {
    if (!dateString) return "N/A";

    const date = new Date(dateString.slice(0, 23));

    if (isNaN(date.getTime())) return "N/A";

    return date.toLocaleString("en-IN", {
      day: "numeric",
      month: "long",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <p className="text-gray-500 text-xl">Loading Prescriptions</p>
      </div>
    );
  }
  return (
    <div className="p-8 bg-gray-50">
      {/** Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-800">My Prescriptions</h1>
        <p className="text-gray-500 mt-1">
          View and download your prescriptions
        </p>
      </div>

      {error && (
        <div className="bg-red-100 text-red-600 p-3 rounded-lg mb-4">
          {error}
        </div>
      )}

      {/** Empty State */}

      {prescriptions.length === 0 ? (
        <div className="bg-white rounded-xl shadow p-12 text-center">
          <p className="text-gray-400 text-xl mb-2">💊 No Prescriptions yet!</p>
          <p className="text-gray-400">
            Wait for your doctor to write a prescription or check with your
            doctor.
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          {prescriptions.map((prescription) => (
            <div
              key={prescription.id}
              className="bg-white rounded-xl shadow p-6"
            >
              {/** Prescription Header */}
              <div className="flex items-start justify-between mb-4">
                <div>
                  <h3 className="text-xl font-bold text-gray-800">
                    {" "}
                    Dr. {doctorNames[prescription.doctorId] || "Loading..."}
                  </h3>
                  <p className="text-gray-500 text-sm mt-1">
                    📅 {formatDate(prescription.prescribedAt)}
                  </p>
                  <p className="text-gray-500 text-sm mt-1">
                    🔗 Appointment:{" "}
                    <span
                      onClick={() => navigate("/patient/appointments")}
                      className="text-blue-600 cursor-pointer hover:underline"
                    >
                      #{prescription.appointmentId}
                    </span>
                  </p>
                </div>
                <span className="bg-green-100 text-green-700 px-4 py-2 rounded-full text-sm font-semibold shrink-0 ml-4">
                  Prescription #{prescription.id}
                </span>
              </div>
              {/** Instructions */}
              <div className="bg-blue-50 rounded-lg p-4 mb-4">
                <p className="font-semibold text-blue-800 mb-1">
                  📋 Instructions:
                </p>
                <p className="text-gray-700">
                  {prescription.instructions || "No instructions provided"}
                </p>
              </div>
              {/** Medicine Table */}
              <div className="mb-4">
                <p className="font-semibold text-gray-700 mb-3">
                  💊 Medicines:
                </p>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="bg-gray-50">
                        <th className="text-left p-3 font-semibold text-gray-600">
                          Medicine
                        </th>
                        <th className="text-left p-3 font-semibold text-gray-600">
                          Dosage
                        </th>
                        <th className="text-left p-3 font-semibold text-gray-600">
                          Frequency
                        </th>
                        <th className="text-left p-3 font-semibold text-gray-600">
                          Duration
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {prescription.medicines.map((medicine, index) => (
                        <tr
                          key={medicine.id}
                          className={
                            index % 2 === 0 ? "bg-white" : "bg-gray-100"
                          }
                        >
                          <td className="p-3 font-medium text-gray-800">
                            {medicine.name}
                          </td>
                          <td className="p-3 text-gray-600">
                            {medicine.dosage}
                          </td>
                          <td className="p-3 text-gray-600">
                            {medicine.frequency}
                          </td>
                          <td className="p-3 text-gray-600">
                            {medicine.duration}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
              {/** Download PDF */}
              <div className="flex justify-end">
                <button
                  onClick={() => handleDownloadPDF(prescription)}
                  className="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition-colors font-medium"
                >
                  📄 Download PDF
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default MyPrescriptions;
